export default {
    FETCH_COUNTRY: 'FETCH_COUNTRY',
    FETCH_COUNTRY_SUCCESS: 'FETCH_COUNTRY_SUCCESS',
    FETCH_COUNTRY_FAILURE: 'FETCH_COUNTRY_FAILURE',
    FETCH_ALL_COUNTRIES: 'FETCH_ALL_COUNTRIES',
    FETCH_COUNTRIES_IN_REGION: 'FETCH_COUNTRIES_IN_REGION',
    FETCH_COUNTRIES_IN_REGION_SUCCESS: 'FETCH_COUNTRIES_IN_REGION_SUCCESS',
    FETCH_COUNTRIES_IN_REGION_FAILURE: 'FETCH_COUNTRIES_IN_REGION_FAILURE',
    FETCH_ALL_SUBREGIONS: 'FETCH_ALL_SUBREGIONS',
    FETCH_ALL_LANGUAGES: 'FETCH_ALL_LANGUAGES'
}